name: Azure function App
on:
  repository_dispatch:
    types: create_function_app
jobs:
  create-function-app:      
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      GITHUB_REPO_NAME: "${{ github.event.client_payload.repo }}"
      AZURE_SUBSCRIPTION: "${{ github.event.client_payload.subscription }}"
      AZURE_RESOURCE_GROUP: "${{ github.event.client_payload.resource_group }}"
      AZURE_DEPLOY_ENVIRONMENT: "${{ github.event.client_payload.environment }}"
      AZURE_FUNCTION_APP_TYPE: "${{ github.event.client_payload.app_type }}"
      AZURE_CLIENT_SECRET: "${{ github.event.client_payload.client_secret }}"
      AZURE_TENANT_ID: "${{ github.event.client_payload.tenant_id }}"
      AZURE_STORAGE_ACCOUNT_NAME: "${{ github.event.client_payload.storage_account_name }}"
      AZURE_FUNCTION_APP_NAME_PREFIX: 'alm-func'
      AZURE_STORAGE_ACCOUNT_NAME_PREFIX: 'almst'
      AZURE_STORAGE_ACCOUNT_SKU: 'Standard_LRS'
      AZURE_FUNCTION_APP_PLAN_SKU: 'EP1'
      AZURE_FUNCTION_APP_WORKERS: '2'
      AZURE_ACR_NAME_PREFIX: 'almacr'
      AZURE_ACR_SKU: 'Standard'
      LOCATION: 'eastus2'
      AZURE_ACR_ADMIN_ENABLED: true
    steps:
    - name: Set env
      run: |
        echo "AZURE_FUNCTION_APP_PLAN=${AZURE_FUNCTION_APP_NAME_PREFIX}-${AZURE_FUNCTION_APP_TYPE}-${AZURE_DEPLOY_ENVIRONMENT}" >> $GITHUB_ENV
        echo "AZURE_FUNCTION_APP_NAME=${AZURE_FUNCTION_APP_NAME_PREFIX}-${AZURE_FUNCTION_APP_TYPE}-${GITHUB_REPO_NAME}-${AZURE_DEPLOY_ENVIRONMENT}" >> $GITHUB_ENV
        echo "AZURE_ACR_NAME=${AZURE_ACR_NAME_PREFIX}${AZURE_DEPLOY_ENVIRONMENT}" >> $GITHUB_ENV
        echo "AZURE_FUNCTION_APP_IMAGE_NAME=${GITHUB_REPO_NAME}-${AZURE_DEPLOY_ENVIRONMENT}" >> $GITHUB_ENV
        echo "AZURE_STORAGE_ACCOUNT=${AZURE_STORAGE_ACCOUNT_NAME_PREFIX}${AZURE_STORAGE_ACCOUNT_NAME}" >> $GITHUB_ENV
        echo "AZURE_CLIENT_ID=echo "::add-mask::"${{ github.event.client_payload.client_id }}"" >> $GITHUB_ENV
    - name: Checkout Code
      uses: actions/checkout@v2
    